server:
  port: 8000
# 路由转发，将/member/...的请求转发了member模块
spring:
  cloud:
    gateway:
      routes:
        - id: member
#          uri: lb://member
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/member/**
